"""
GEPPETTO 3: MEETING NOTES GENERATOR
=====================================
Generates a structured end-of-meeting brief from the session transcript and
alerts, then saves it to two locations:

  docs/notes/YYYY-MM-DD-<slug>.md   (tier: derived — picked up by next kb_sync)
  meetings/<folder>/notes.md         (permanent record alongside transcript)

The brief format mirrors the 'brief' skill for Team audience:
  ## Current Status
  ## Key Achievements
  ## Upcoming Priorities
  ## Risks & Issues
  ## Decisions / Support Needed
  ## Action Items  (owner · due date)

Two Haiku calls are made:
  1. Slug generation — 2-4 word kebab-case label from transcript content
  2. Brief generation — structured markdown brief

Usage (called by phase3_server_realtime.py after session_end):
  from meeting_notes import generate_meeting_notes
  path = generate_meeting_notes(
      transcript=session.rolling_transcript,
      alerts=session.alerts,
      docs_dir="./docs",
      meeting_folder="./meetings/2026-06-17-abc123",
      anthropic_client=client,
  )
"""

import os
import re
import logging
from datetime import date, datetime, timezone

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

_SLUG_PROMPT = """\
Given the following meeting transcript excerpt, generate a 2-4 word kebab-case
label that captures the main topic (e.g. "qa-status-review", "sprint-planning",
"release-readout", "budget-alignment").

TRANSCRIPT (first 800 chars):
{excerpt}

Respond with ONLY the slug — lowercase, hyphens, no spaces, no punctuation.
Max 40 characters."""


_BRIEF_PROMPT = """\
You are a project management assistant. Generate a structured meeting brief
from the transcript and validation alerts below.

DATE: {meeting_date}
TRANSCRIPT:
{transcript}

VALIDATION ALERTS (category | claim | action):
{alerts_text}

Write the brief in this exact markdown format. Be concise and specific.
Use bullet points within each section. If a section has nothing to report,
write "Nothing to report."

## Current Status
[Overall project state based on what was discussed]

## Key Achievements
[Completed work, milestones reached, or progress confirmed in this meeting]

## Upcoming Priorities
[Next steps, upcoming deadlines, or work planned]

## Risks & Issues
[Any risks, blockers, concerns, or CONTRADICTED/OUTDATED facts surfaced]

## Decisions / Support Needed
[Decisions made or open questions requiring stakeholder input]

## Action Items
[Specific tasks with owner and due date. Format: - Task description · Owner · Due]

---
*Auto-generated by Geppetto 3 — review before sharing.*"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_slug(transcript: str, anthropic_client) -> str:
    """Generate a 2-4 word kebab-case slug via Haiku."""
    try:
        excerpt = transcript[:800].strip()
        response = anthropic_client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=20,
            messages=[{"role": "user", "content": _SLUG_PROMPT.format(excerpt=excerpt)}]
        )
        raw = response.content[0].text.strip().lower()
        # Sanitize: keep only alphanumeric and hyphens, collapse extras
        slug = re.sub(r'[^a-z0-9-]', '-', raw)
        slug = re.sub(r'-{2,}', '-', slug).strip('-')
        return slug[:40] or "meeting"
    except Exception as e:
        logger.warning("slug generation failed: %s", e)
        return "meeting"


def _format_alerts(alerts: list) -> str:
    """Convert alert list to a compact text summary for the brief prompt."""
    if not alerts:
        return "(no claims validated)"
    lines = []
    for a in alerts:
        cat   = a.get("category", "?")
        claim = a.get("claim_text", "")[:120]
        action = a.get("suggested_response", "")[:100]
        lines.append(f"  [{cat}] {claim} → {action}")
    return "\n".join(lines[:30])  # cap at 30 alerts to stay within token limits


def _make_brief(transcript: str, alerts: list, meeting_date: str,
                anthropic_client) -> str:
    """Generate the structured brief via Haiku."""
    # Truncate very long transcripts
    max_transcript = 4000
    trunc = transcript[:max_transcript]
    if len(transcript) > max_transcript:
        trunc += "\n\n[... transcript truncated ...]"

    alerts_text = _format_alerts(alerts)

    try:
        response = anthropic_client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=1200,
            messages=[{"role": "user", "content": _BRIEF_PROMPT.format(
                meeting_date=meeting_date,
                transcript=trunc,
                alerts_text=alerts_text,
            )}]
        )
        return response.content[0].text.strip()
    except Exception as e:
        logger.error("brief generation failed: %s", e)
        # Fallback: minimal brief from alerts only
        contradicted = [a for a in alerts if a.get("category") == "CONTRADICTED"]
        outdated     = [a for a in alerts if a.get("category") == "OUTDATED"]
        lines = [
            f"## Current Status\nBrief generation failed ({e}). Manual review required.",
            "## Key Achievements\nNothing to report.",
            "## Upcoming Priorities\nNothing to report.",
        ]
        if contradicted or outdated:
            risks = "\n".join(
                f"- {a.get('claim_text','')}" for a in (contradicted + outdated)[:10]
            )
            lines.append(f"## Risks & Issues\n{risks}")
        else:
            lines.append("## Risks & Issues\nNothing to report.")
        lines += [
            "## Decisions / Support Needed\nNothing to report.",
            "## Action Items\nNothing to report.",
            "\n---\n*Auto-generated by Geppetto 3 — review before sharing.*",
        ]
        return "\n\n".join(lines)


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def generate_meeting_notes(
    transcript: str,
    alerts: list,
    docs_dir: str,
    meeting_folder: str,
    anthropic_client,
) -> dict:
    """
    Generate and save end-of-meeting notes.

    Args:
        transcript:       Full session rolling transcript.
        alerts:           List of alert dicts from the session.
        docs_dir:         Path to docs/ directory (notes saved to docs/notes/).
        meeting_folder:   Path to the meeting's saved folder (notes.md saved here).
        anthropic_client: Anthropic client instance.

    Returns:
        dict with keys: notes_path (docs/notes/), meeting_path, filename, slug
    """
    if not transcript or not transcript.strip():
        logger.warning("generate_meeting_notes: empty transcript, skipping")
        return {}

    today         = date.today().isoformat()
    slug          = _make_slug(transcript, anthropic_client)
    filename      = f"{today}-{slug}.md"
    brief_content = _make_brief(transcript, alerts, today, anthropic_client)

    # Header metadata
    header = (
        f"# Meeting Notes — {today}\n\n"
        f"**Slug:** {slug}  \n"
        f"**Claims validated:** {len(alerts)}  \n"
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}  \n\n"
        f"---\n\n"
    )
    full_content = header + brief_content

    result = {}

    # Save to docs/notes/ (derived tier — picked up by next kb_sync)
    notes_dir = os.path.join(docs_dir, "notes")
    os.makedirs(notes_dir, exist_ok=True)
    notes_path = os.path.join(notes_dir, filename)
    try:
        with open(notes_path, "w", encoding="utf-8") as f:
            f.write(full_content)
        result["notes_path"] = notes_path
        logger.info("Meeting notes saved to %s", notes_path)
    except Exception as e:
        logger.error("Could not save notes to docs/notes/: %s", e)

    # Save to meeting folder
    if meeting_folder and os.path.isdir(meeting_folder):
        meeting_path = os.path.join(meeting_folder, "notes.md")
        try:
            with open(meeting_path, "w", encoding="utf-8") as f:
                f.write(full_content)
            result["meeting_path"] = meeting_path
        except Exception as e:
            logger.error("Could not save notes to meeting folder: %s", e)

    result["filename"] = filename
    result["slug"]     = slug
    return result
